---
- name: Setup passwordless sudo for ccason user
  hosts: all
  become: yes
  tasks:
    - name: Add ccason to passwordless sudo
      copy:
        dest: /etc/sudoers.d/ccason
        content: |
          ccason ALL=(ALL) NOPASSWD:ALL
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Test passwordless sudo
      command: sudo -n whoami
      become: no
      register: sudo_test
      changed_when: false

    - name: Display sudo test result
      debug:
        msg: "Passwordless sudo test: {{ sudo_test.stdout }}"