- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes
  become: yes

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  become: yes
  notify:
    - Restart keepalived

- name: Enable and start keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
  become: yes