- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes
  become: yes

- name: Create keepalived config directory
  file:
    path: /etc/keepalived
    state: directory
    mode: '0755'
  become: yes

- name: Install API server health check script
  template:
    src: check-apiserver.sh.j2
    dest: /usr/local/bin/check-apiserver.sh
    mode: '0755'
  become: yes
  notify:
    - Restart keepalived

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  become: yes
  notify:
    - Restart keepalived

- name: Enable and start keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
  become: yes