apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temperature-exporter
  namespace: monitoring
  labels:
    app: temperature-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: temperature-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reboot-exporter
  namespace: monitoring
  labels:
    app: reboot-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: reboot-exporter
  endpoints:
  - port: metrics
    interval: 300s
    path: /metrics